version: '3'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
        NODE_ENV: production
        DATABASE_URL: ${DATABASE_URL}
    restart: always
    ports:
      - "3000:3000"